---
title: "Influence of parameters"
author: "Morgane Pierre-Jean"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Influence of parameters}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{tibble}
---

```{r}
library(ggplot2)
library(tibble)
library(dplyr)
library(CrIMMix)
```

## Define paramaters for simulations

```{r}
means <- c(2,2,2,2)
sds <- c(1,1,1,1)
params <- mapply(function (m, sd) return(c(mean=m, sd=sd)), means, sds, SIMPLIFY=FALSE)
params_beta <- list(c(mean1=-2, mean2=2, sd1=0.5, sd2=0.5))
S <- 50
nclust=4
n_byClust=c(10,20,5,25)
```

```{r}
noiseD1=c(0.2)
noiseD2=c(0.1)/10
noiseD3=c(0.1)*3
props <- c(0.005, 0.01, 0.02)
```

## Simulations of data sets
```{r}
dat1 <- simulateY(nclust=nclust,n_byClust=n_byClust, J=1000,
                  prop=props[1],params=params, noise=noiseD1)
Y1 <- dat1$data
colnames(Y1) <- sprintf("gene%s", 1:ncol(Y1))


dat2 <- simulateY(nclust=nclust,n_byClust=n_byClust, J=500, flavor="binary",
                  params=list(c(p=0.6)), prop=props[2], noise=noiseD2)

Y2 <- dat2$data
colnames(Y2) <- sprintf("gene%s", 1:ncol(Y2))

dat3 <- simulateY(nclust=nclust,n_byClust=n_byClust, J=5000,
                  flavor="beta", params=params_beta, prop=props[3], noise=noiseD3)
Y3 <- dat3$data
colnames(Y3) <- sprintf("gene%s", 1:ncol(Y3))


sim <- list(data= list(dat1=Y1, dat2= Y2,dat3=Y3),
            biomark = list(dat1=dat1$positive,
                           dat2=dat2$positive, 
                           dat3=dat3$positive),
            true.clust = dat1$true.clusters)

truth <- lapply(lapply(sim$biomark, unlist), unique)

```

## Influence number of components

### MoCluster
```{r}
k.grid=c(0.05,0.4, 0.1)%*%t(c(0.1, 0.2,0.5,1,2,5,10))
ncomp.grid <- 1:8
```
```{r}
Moaresults <- lapply(ncomp.grid,  IntMultiOmics, method="Mocluster",
                    data=sim$data, k=c(0.05*2, 0.05*2, 0.1), K=4 )

```


```{r}
auc_eval_moclust <- sapply (Moaresults, function(mm) {
  roc_eval(truth= truth, fit = mm$fit, method = "Mocluster")
}, simplify = FALSE)

```

```{r}
g_moclust <- do.call(rbind, lapply(1:length(auc_eval_moclust), function (ss) {
  dd <- auc_eval_moclust[[ss]]
  n_by_data_set <- sapply(dd$TPR, length)
  tprs <- dd$TPR %>% unlist
  fprs <- dd$FPR %>% unlist
  data.frame(TPR=tprs, FPR=fprs,
             dataSet= sprintf("data set %s", rep(1:3, times=n_by_data_set)),
             k=as.factor(ss))
}))
```

```{r}
g_moclust %>% ggplot(aes(x=FPR, y=TPR, color=k))+geom_line()+facet_grid(dataSet~.)+theme_bw()

```

### SGCCA

```{r}
ncomp.grid <- rep(1:8,length(sim$data)) %>% matrix(ncol=3)
SGCCAresults <- apply(ncomp.grid,  1, IntMultiOmics, method="SGCCA",
                     data=sim$data, C=1-diag(length(sim$data)),c1=c(0.3, 0.3,0.4), K=4)
```
```{r}
auc_eval_SGCCA <- sapply (SGCCAresults, function(mm) {
  roc_eval(truth= truth, fit = mm$fit, method = "SGCCA")
}, simplify = FALSE)

```


```{r}
g_sgcca <- do.call(rbind, lapply(1:length(auc_eval_SGCCA), function (ss) {
  dd <- auc_eval_SGCCA[[ss]]
  n_by_data_set <- sapply(dd$TPR, length)
  tprs <- dd$TPR %>% unlist
  fprs <- dd$FPR %>% unlist
  data.frame(TPR=tprs, FPR=fprs,
             dataSet= sprintf("data set %s", rep(1:3, times=n_by_data_set)),
             k=as.factor(ss))
}))
```


```{r}
g_sgcca %>% ggplot(aes(x=FPR, y=TPR, color=k))+geom_line()+facet_grid(dataSet~.)+theme_bw()

```


## Influence sparse parameter

### MoCluster
```{r}
k.grid=c(0.05,0.4, 0.1)%*%t(c(0.1, 0.2,0.5,1,2,5,10))
```
```{r}
Moaresults_k <- apply(k.grid,2,  IntMultiOmics, method="Mocluster",
                    data=sim$data, K=4, ncomp=3)

```


```{r}
auc_eval_moclust_k <- sapply (Moaresults_k, function(mm) {
  roc_eval(truth= truth, fit = mm$fit, method = "Mocluster")
}, simplify = FALSE)

```

```{r}
g_moclust_k <- do.call(rbind, lapply(1:length(auc_eval_moclust_k), function (ss) {
  dd <- auc_eval_moclust_k[[ss]]
  n_by_data_set <- sapply(dd$TPR, length)
  tprs <- dd$TPR %>% unlist
  fprs <- dd$FPR %>% unlist
  data.frame(TPR=tprs, FPR=fprs,
             dataSet= sprintf("data set %s", rep(1:3, times=n_by_data_set)),
            lambda=sprintf("lambda %s", as.factor(ss)))
}))
```

```{r}
g_moclust_k %>% ggplot(aes(x=FPR, y=TPR, color=lambda))+geom_line()+facet_grid(dataSet~.)+theme_bw()

```

### SGCCA

```{r}
c1.grid <-c(0.3, 0.3,0.4)%*%t(c(0.2,0.5,1,2))
SGCCAresults_k <- apply(c1.grid,  2, IntMultiOmics, method="SGCCA",
                     data=sim$data, K=4, C=1-diag(length(sim$data)), ncomp=rep(3,3))
```
```{r}
auc_eval_SGCCA_k <- sapply (SGCCAresults_k, function(mm) {
  roc_eval(truth= truth, fit = mm$fit, method = "SGCCA")
}, simplify = FALSE)

```


```{r}
g_sgcca_k <- do.call(rbind, lapply(1:length(auc_eval_SGCCA_k), function (ss) {
  dd <- auc_eval_SGCCA_k[[ss]]
  n_by_data_set <- sapply(dd$TPR, length)
  tprs <- dd$TPR %>% unlist
  fprs <- dd$FPR %>% unlist
  data.frame(TPR=tprs, FPR=fprs,
             dataSet= sprintf("data set %s", rep(1:3, times=n_by_data_set)),
             lambda=sprintf("lambda %s", as.factor(ss)))
}))
```


```{r}
g_sgcca_k %>% ggplot(aes(x=FPR, y=TPR, color=lambda))+geom_line()+facet_grid(dataSet~.)+theme_bw()

```
